[2021-11-27 09:50:09,366] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:49:00+00:00 [queued]>
[2021-11-27 09:50:09,371] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:49:00+00:00 [queued]>
[2021-11-27 09:50:09,372] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:50:09,372] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 09:50:09,372] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:50:09,378] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-11-27 02:49:00+00:00
[2021-11-27 09:50:09,380] {standard_task_runner.py:52} INFO - Started process 5028 to run task
[2021-11-27 09:50:09,385] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elt', 'upload', 'scheduled__2021-11-27T02:49:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/processing.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp9qk9e3lf', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpbd3a5hne']
[2021-11-27 09:50:09,387] {standard_task_runner.py:77} INFO - Job 231: Subtask upload
[2021-11-27 09:50:09,416] {logging_mixin.py:109} INFO - Running <TaskInstance: elt.upload scheduled__2021-11-27T02:49:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 09:50:09,449] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elt
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-11-27T02:49:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-27T02:49:00+00:00
[2021-11-27 09:50:09,450] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 09:50:09,450] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/cleaning.py /Users/Home/Airflow/output worldbank']
[2021-11-27 09:50:09,456] {subprocess.py:85} INFO - Output:
[2021-11-27 09:50:09,521] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SH.STA.MMRT_DS2_en_csv_v2_3159367.csv: No such file or directory
[2021-11-27 09:50:09,526] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SH.DYN.MORT_DS2_en_csv_v2_3162033.csv: No such file or directory
[2021-11-27 09:50:09,531] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.GN.ZS_DS2_en_csv_v2_3161196.csv: No such file or directory
[2021-11-27 09:50:09,536] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.MP.ZS_DS2_en_csv_v2_3161055.csv: No such file or directory
[2021-11-27 09:50:09,542] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.XP.ZS_DS2_en_csv_v2_3164297.csv: No such file or directory
[2021-11-27 09:50:09,547] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.GI.ZS_DS2_en_csv_v2_3164289.csv: No such file or directory
[2021-11-27 09:50:09,547] {subprocess.py:89} INFO - API_SH.STA.MMRT_DS2_en_csv_v2_3159367.csv
[2021-11-27 09:50:09,547] {subprocess.py:89} INFO - API_SH.DYN.MORT_DS2_en_csv_v2_3162033.csv
[2021-11-27 09:50:09,547] {subprocess.py:89} INFO - API_DT.ODA.ODAT.GN.ZS_DS2_en_csv_v2_3161196.csv
[2021-11-27 09:50:09,548] {subprocess.py:89} INFO - API_DT.ODA.ODAT.MP.ZS_DS2_en_csv_v2_3161055.csv
[2021-11-27 09:50:09,548] {subprocess.py:89} INFO - API_DT.ODA.ODAT.XP.ZS_DS2_en_csv_v2_3164297.csv
[2021-11-27 09:50:09,548] {subprocess.py:89} INFO - API_DT.ODA.ODAT.GI.ZS_DS2_en_csv_v2_3164289.csv
[2021-11-27 09:50:09,551] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-27 09:50:09,565] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=elt, task_id=upload, execution_date=20211127T024900, start_date=20211127T025009, end_date=20211127T025009
[2021-11-27 09:50:09,610] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-27 09:50:09,630] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
