[2021-11-27 09:48:11,788] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:47:00+00:00 [queued]>
[2021-11-27 09:48:11,797] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:47:00+00:00 [queued]>
[2021-11-27 09:48:11,797] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:48:11,797] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 09:48:11,797] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:48:11,805] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-11-27 02:47:00+00:00
[2021-11-27 09:48:11,807] {standard_task_runner.py:52} INFO - Started process 4898 to run task
[2021-11-27 09:48:11,814] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elt', 'upload', 'scheduled__2021-11-27T02:47:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/processing.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp808uhlyc', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpicj5etbo']
[2021-11-27 09:48:11,817] {standard_task_runner.py:77} INFO - Job 225: Subtask upload
[2021-11-27 09:48:11,856] {logging_mixin.py:109} INFO - Running <TaskInstance: elt.upload scheduled__2021-11-27T02:47:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 09:48:11,897] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elt
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-11-27T02:47:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-27T02:47:00+00:00
[2021-11-27 09:48:11,898] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 09:48:11,899] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/cleaning.py /Users/Home/Airflow/output worldbank']
[2021-11-27 09:48:11,908] {subprocess.py:85} INFO - Output:
[2021-11-27 09:48:11,992] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.FRST.K2_DS2_en_csv_v2_3159335.csv: No such file or directory
[2021-11-27 09:48:11,998] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.CON.FERT.ZS_DS2_en_csv_v2_3159437.csv: No such file or directory
[2021-11-27 09:48:12,004] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.TOTL.K2_DS2_en_csv_v2_3159087.csv: No such file or directory
[2021-11-27 09:48:12,010] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.CREL.HA_DS2_en_csv_v2_3163897.csv: No such file or directory
[2021-11-27 09:48:12,015] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.FRST.ZS_DS2_en_csv_v2_3158992.csv: No such file or directory
[2021-11-27 09:48:12,021] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.PRD.FOOD.XD_DS2_en_csv_v2_3159905.csv: No such file or directory
[2021-11-27 09:48:12,026] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SL.AGR.EMPL.MA.ZS_DS2_en_csv_v2_3165572.csv: No such file or directory
[2021-11-27 09:48:12,027] {subprocess.py:89} INFO - API_AG.LND.FRST.K2_DS2_en_csv_v2_3159335.csv
[2021-11-27 09:48:12,027] {subprocess.py:89} INFO - API_AG.CON.FERT.ZS_DS2_en_csv_v2_3159437.csv
[2021-11-27 09:48:12,027] {subprocess.py:89} INFO - API_AG.LND.TOTL.K2_DS2_en_csv_v2_3159087.csv
[2021-11-27 09:48:12,027] {subprocess.py:89} INFO - API_AG.LND.CREL.HA_DS2_en_csv_v2_3163897.csv
[2021-11-27 09:48:12,027] {subprocess.py:89} INFO - API_AG.LND.FRST.ZS_DS2_en_csv_v2_3158992.csv
[2021-11-27 09:48:12,028] {subprocess.py:89} INFO - API_AG.PRD.FOOD.XD_DS2_en_csv_v2_3159905.csv
[2021-11-27 09:48:12,028] {subprocess.py:89} INFO - API_SL.AGR.EMPL.MA.ZS_DS2_en_csv_v2_3165572.csv
[2021-11-27 09:48:12,031] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-27 09:48:12,045] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=elt, task_id=upload, execution_date=20211127T024700, start_date=20211127T024811, end_date=20211127T024812
[2021-11-27 09:48:12,082] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-27 09:48:12,095] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
