[2021-11-27 11:30:08,877] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T04:29:00+00:00 [queued]>
[2021-11-27 11:30:08,883] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T04:29:00+00:00 [queued]>
[2021-11-27 11:30:08,883] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 11:30:08,883] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 11:30:08,883] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 11:30:08,890] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-11-27 04:29:00+00:00
[2021-11-27 11:30:08,892] {standard_task_runner.py:52} INFO - Started process 10754 to run task
[2021-11-27 11:30:08,896] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elt', 'upload', 'scheduled__2021-11-27T04:29:00+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/processing.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmph49m5bti', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp8r0sz6w9']
[2021-11-27 11:30:08,897] {standard_task_runner.py:77} INFO - Job 537: Subtask upload
[2021-11-27 11:30:08,924] {logging_mixin.py:109} INFO - Running <TaskInstance: elt.upload scheduled__2021-11-27T04:29:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 11:30:08,951] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elt
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-11-27T04:29:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-27T04:29:00+00:00
[2021-11-27 11:30:08,952] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 11:30:08,952] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/cleaning.py /Users/Home/Airflow/output worldbank']
[2021-11-27 11:30:08,957] {subprocess.py:85} INFO - Output:
[2021-11-27 11:30:09,006] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.CROP.ZS_DS2_en_csv_v2_3163899.csv: No such file or directory
[2021-11-27 11:30:09,011] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.PRD.LVSK.XD_DS2_en_csv_v2_3161120.csv: No such file or directory
[2021-11-27 11:30:09,016] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.TOTL.K2_DS2_en_csv_v2_3159087.csv: No such file or directory
[2021-11-27 11:30:09,021] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SP.RUR.TOTL.ZS_DS2_en_csv_v2_3160121.csv: No such file or directory
[2021-11-27 11:30:09,026] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.CREL.HA_DS2_en_csv_v2_3163897.csv: No such file or directory
[2021-11-27 11:30:09,030] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SP.RUR.TOTL_DS2_en_csv_v2_3163192.csv: No such file or directory
[2021-11-27 11:30:09,031] {subprocess.py:89} INFO - API_AG.LND.CROP.ZS_DS2_en_csv_v2_3163899.csv
[2021-11-27 11:30:09,031] {subprocess.py:89} INFO - API_AG.PRD.LVSK.XD_DS2_en_csv_v2_3161120.csv
[2021-11-27 11:30:09,031] {subprocess.py:89} INFO - API_AG.LND.TOTL.K2_DS2_en_csv_v2_3159087.csv
[2021-11-27 11:30:09,031] {subprocess.py:89} INFO - API_SP.RUR.TOTL.ZS_DS2_en_csv_v2_3160121.csv
[2021-11-27 11:30:09,032] {subprocess.py:89} INFO - API_AG.LND.CREL.HA_DS2_en_csv_v2_3163897.csv
[2021-11-27 11:30:09,032] {subprocess.py:89} INFO - API_SP.RUR.TOTL_DS2_en_csv_v2_3163192.csv
[2021-11-27 11:30:09,035] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-27 11:30:09,051] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=elt, task_id=upload, execution_date=20211127T042900, start_date=20211127T043008, end_date=20211127T043009
[2021-11-27 11:30:09,079] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-27 11:30:09,098] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
